-- sudo su postgres
-- createuser clothes_user
-- createdb clothes_db --owner clothes_user
-- psql
-- alter user clothes_user with password '12345';
-- \q
-- psql clothes_db

DROP TABLE IF EXISTS brands CASCADE;
CREATE TABLE brands (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" character varying(100),
    "origin" character varying(100)
);

DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"price" integer,
"stock" integer,
"gender" integer,
"brand_id" integer,
    CONSTRAINT fk_brands
          FOREIGN KEY(brand_id) 
              REFERENCES brands(id)
              ON DELETE CASCADE
);


REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO clothes_user;

REVOKE ALL ON products FROM public;
GRANT ALL ON products TO clothes_user;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO clothes_user;

REVOKE ALL ON brands FROM public;
GRANT ALL ON brands TO clothes_user;

INSERT INTO brands (name, origin) VALUES ('Gucci', 'Francia');
INSERT INTO brands (name, origin) VALUES ('Guess', 'Alemania');
INSERT INTO brands (name, origin) VALUES ('Hermes', 'Estados Unidos');

INSERT INTO products (name, price, stock, gender, brand_id) VALUES ('pantalones', 2000, 6, 1, 1);
INSERT INTO products (name, price, stock, gender, brand_id) VALUES ('camiseta', 2200, 4, 1, 2);
INSERT INTO products (name, price, stock, gender, brand_id) VALUES ('chaqueta', 1000, 1, 1, 3);
INSERT INTO products (name, price, stock, gender, brand_id) VALUES ('camisa', 3300, 7, 1, 1);
INSERT INTO products (name, price, stock, gender, brand_id) VALUES ('calcetines', 500, 0, 1, 2);
INSERT INTO products (name, price, stock, gender, brand_id) VALUES ('blusa', 1800, 1, 2, 3);
INSERT INTO products (name, price, stock, gender, brand_id) VALUES ('vestido', 4500, 4, 2, 1);
INSERT INTO products (name, price, stock, gender, brand_id) VALUES ('falda', 3000, 2, 2, 2);
INSERT INTO products (name, price, stock, gender, brand_id) VALUES ('medias', 1000, 0, 2, 3);
INSERT INTO products (name, price, stock, gender, brand_id) VALUES ('zapatos de tacón', 3400, 3, 2, 1);

-- \q
-- exit