DROP TABLE IF EXISTS dishes CASCADE;
CREATE TABLE dishes (
"name" character GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"price" integer varying(100),
"type" integer varying(64)
);

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO menuqr_user;

REVOKE ALL ON dishes FROM public;
GRANT ALL ON dishes TO menuqr_user;

