-- sudo su postgres
-- createuser (nombre_que_se_quiera);
-- createdb (nombre_que_se_quiera) --owner (usuario_de_arriba);
-- psql
-- alter user (usuario_de_arriba) with password '(a_elegir)';
-- \q
-- psql (nombre_BBDD);

DROP TABLE IF EXISTS scores CASCADE;
CREATE TABLE scores (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"time" integer 
);


REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO marcianos_user;

REVOKE ALL ON users FROM public;
GRANT ALL ON users TO marcianos_user;
